POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "my2@email.com",
  "password": "verysecret123"
}

### 

POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "my@email.com",
  "password": "verysecret123"
}

### 