GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjQ3MjY0NDM5LCJleHAiOjE2NDcyNjgwMzl9.CsRS0hbYgSIbreKwknoay1BCQvzrw_mZF96v-1f2AVs

###
GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjQ2O
###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "my2@email.com",
  "password": "verysecret123"
}

### 

POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "my@email.com",
  "password": "verysecret123"
}

###  verysecret123


GET http://localhost:3000/user-tutorials/6

###
GET http://localhost:3000/tutorials
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjQ3MjY0NDM5LCJleHAiOjE2NDcyNjgwMzl9.CsRS0hbYgSIbreKwknoay1BCQvzrw_mZF96v-1f2AVs
###